id = "vscode-great-icons"
name = "VSCode Great Icons Theme"
version = "0.1.0"
schema_version = 1
authors = ["Randa Zraik <randazraik@outlook.com>"]
description = "VSCode great icons theme for Zed"
repository = "https://github.com/randazraik/zed-vscode-great-icons"
